### ISSUE TITLE
Using Custom Type causes cPickle.PicklingError

### ISSUE THREAD

**Issue by primoz-k** [datamade/dedupe#411] opened 2015-08-24 10:22 UTC
This is my variable definition:
```python

def position_comparator(first_position, second_position):
    # custom comparation of these two strings, returns float
    # ...
    return 0.0  # dummy result

fields = [
    {'field': 'url', 'type': 'String'},
    {'field': 'first_name', 'type': 'String'},
    {'field': 'last_name', 'type': 'String'},
    {'field': 'address', 'type': 'String'},
    {'field': 'positions', 'type': 'Custom', 'comparator': position_comparator}
]

data_d = readData(inputFile)

deduper = dedupe.Dedupe(fields)

deduper.sample(data_d, 15000)
```

and the `.sample()` call returns

```python
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pk6730/env/migration/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/pk6730/env/migration/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/pk6730/env/migration/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/pk6730/env/migration/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/pk6730/env/migration/scraper/scraper_app/management/commands/deduplicate.py", line 507, in handle
    deduper.sample(data_d, 15000)
  File "/home/pk6730/env/migration/local/lib/python2.7/site-packages/dedupe/api.py", line 957, in sample
    self._loadSample(data_sample)
  File "/home/pk6730/env/migration/local/lib/python2.7/site-packages/dedupe/api.py", line 902, in _loadSample
    self.num_cores)
  File "/home/pk6730/env/migration/local/lib/python2.7/site-packages/dedupe/training.py", line 55, in __init__
    1))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

```

If I don't use field with custom comparator, everything works fine. Is this a bug, or am I doing something wrong?

Thanks.

**Comment by fgregg** [comment] 2015-08-24 13:10
I can't reproduce. Can you post the full code that causes this error.

**Comment by primoz-k** [comment] 2015-08-24 13:49
Here it is: https://gist.github.com/primoz-k/bd3baaaa5e4bcdfd3c6b

Let me know if you need anything else, thanks.

**Comment by primoz-k** [comment] 2015-08-27 08:04
Just checking if you had a chance to look at this? I can not spot an obvious problem in my code. I'm using Python 2.7.6

**Comment by fgregg** [comment] 2015-08-27 14:40
Sorry. I made a note on this gist, but I guess it didn't notify you. Could
you provide some example data so that I can run you code. (Doesn't have to
be long and can be dummy data)

**Comment by primoz-k** [comment] 2015-08-28 08:42
I made a comment on gist, but as I did a little research, comments do not trigger notifications on gists, so I am just making sure that you will see it.

**Comment by fgregg** [comment] 2015-08-28 13:01
Great! I'll take a look.

**Comment by primoz-k** [comment] 2015-09-11 12:39
Any progress? No pressure. :)

**Comment by fgregg** [comment] 2015-09-13 09:58
I can't run your example. It has many dependencies that you have not included included and you are not constructing cp objects from the csv file in a way that your comparator function seems to expect. Please update your code so that it runs until it gets to the error that you are seeing here.

**Comment by fgregg** [comment] 2015-09-19 12:24
Closing for now. 

@primoz-k if you can provide a reproducible example, I'll be happy to take a look.

**Closed by fgregg** 2015-09-19 12:24 UTC

**Comment by primoz-k** [comment] 2015-09-22 08:24
@fgregg Sorry for such a late reply. It was a problem in my code. If anybody else gets this error, they should inspect their custom comparator. It all works now, thanks.
