### ISSUE TITLE
Different errors when  running dedupe under 2 operating systems

### ISSUE THREAD

**Issue by L-Jiang** [datamade/dedupe#345] opened 2015-01-30 21:47 UTC
Recently I'm trying to install the dedupe program on 2 different OS systems: Windows Server 2008 and Win 7 Professional and I'm experiencing issues on both.

The versions of the relevant programs are as below:
Python: 2.7.5 | Anaconda 2.1.0 (64-bit)
Eclipse: Indigo Service Release 2
Numpy: 1.9.0
Dedupe: Most recent

On Windows Server 2008:

I completed training, and then I got the following error:
Traceback (most recent call last):
  File "C:\Users\Administrator.TOM\Documents\Hawk\Dedupe\csv_example.py",
line 135, in <module>
    deduper.train()
  File "C:\Anaconda\lib\site-packages\dedupe\api.py", line 691, in train
    self._trainBlocker(ppc, uncovered_dupes)
  File "C:\Anaconda\lib\site-packages\dedupe\api.py", line 719, in
_trainBlocker
    self._linkage_type)
  File "C:\Anaconda\lib\site-packages\dedupe\training.py", line 139, in
blockTraining
    dupe_pairs | distinct_pairs)
  File "C:\Anaconda\lib\site-packages\dedupe\training.py", line 304, in
__init__
    blocker.tfIdfBlock(field_records, field)
  File "C:\Anaconda\lib\site-packages\dedupe\blocking.py", line 80, in
tfIdfBlock
    index.index(record_id, doc)
  File "C:\Anaconda\lib\site-packages\dedupe\tfidf.py", line 28, in index
    self._index.index_doc(i, doc)
  File "C:\Anaconda\lib\site-packages\zope\index\text\textindex.py", line
50, in index_doc
    self.index.index_doc(docid, text)
  File "C:\Anaconda\lib\site-packages\zope\index\text\baseindex.py", line
96, in index_doc
    if docid in self._docwords:
TypeError: expected integer key

On Win 7 Professional:

I did not even get to the "training" this time. The error is:

Traceback (most recent call last):
  File "D:\Documents\Hawk_Test\Dedupe\csv_example(1).py", line 26, in
<module>
    import dedupe
  File "D:\Anaconda\lib\site-packages\dedupe\__init__.py", line 14, in
<module>
    from api import StaticDedupe, Dedupe
  File "D:\Anaconda\lib\site-packages\dedupe\api.py", line 24, in <module>
    import dedupe.training as training
  File "D:\Anaconda\lib\site-packages\dedupe\training.py", line 10, in
<module>
    import predicates
  File "D:\Anaconda\lib\site-packages\dedupe\predicates.py", line 8, in
<module>
    from dedupe.cpredicates import ngrams, initials
ImportError: DLL load failed: A dynamic link library (DLL) initialization
routine failed.

**Comment by fgregg** [comment] 2015-01-30 22:34
For the first problem, is 'csv_example.py' the exact same file as https://github.com/datamade/dedupe-examples/tree/master/csv_example?

For the second problem, what steps are you taking to build dedupe on windows 7?

**Comment by L-Jiang** [comment] 2015-02-02 20:27
For the first problem, yes, it is exact the same file and I used the input "csv_example_messy_input" file for testing.

For the second problem, I installed Anaconda and then ran "pip install dedupe".

**Comment by fgregg** [comment] 2015-02-04 22:03
Hmm.. I'm sorry, I don't really have access to these operating systems to track this down, and I can't reproduce on the machines I can get to.

**Comment by la-perte** [comment] 2015-02-05 19:44
I'm having the same issue as the first problem on Windows Server 2012.

**Comment by fgregg** [comment] 2015-02-09 21:01
Try the newest version, please.

**Comment by fgregg** [comment] 2015-02-12 21:55
Closing for now. If it still doesn't work with the new version, feel free to reopen.

**Closed by fgregg** 2015-02-12 21:55 UTC

**Comment by L-Jiang** [comment] 2015-02-12 22:44
I tried the new dedupe folder from datamade/dedupe with "Fix #353 by using simplejson where available" and updated csv_example.py. Still getting the same error on Win 7.

Will try on Windows Server 2008 tomorrow.

**Comment by fgregg** [comment] 2015-02-12 22:50
Thanks, let me know what happens with Windows 2008.
